### ISSUE TITLE
Implementing WooCommerce Subscription

### ISSUE THREAD

**Issue by alexasomba** [tubiz/woo-rave#1]
Nicely done, great one!
Is there a milestone for integrating this plugin with WooCommerce Subscription?

**Comment by tubiz** [comment]
Yes. Support for WooCommerce Subscriptions will be added next month.

Which of the WooCommerce Subscriptions plugins are you using?

**Comment by alexasomba** [comment]
Oh, great!
The WooCommerce Subscription plugin supported by WooCommerce. That's this: https://woocommerce.com/products/woocommerce-subscriptions/

**Comment by tubiz** [comment]
Version 2.0.0 https://wordpress.org/plugins/woo-rave/ has been released with support for WooCommerce subscriptions.
