### ISSUE TITLE
Merchant cannot accept international payments

### ISSUE THREAD

**Issue by Vorteri** [tubiz/woo-rave#11]
![09 08 2022_15 12 00_REC](https://user-images.githubusercontent.com/22683685/183644510-19464cce-87d9-4cd6-b4d6-1d5ed9bd5b47.png)
Problem with payment, international mode. That is, I cannot pay in dollars, it throws this error. Default payment is UGX

We could not charge this card. Reason: Merchant cannot accept international payments at this time. Please contact support

**Comment by celebrity1** [comment]
It is an issue with the payment aggregator. For reference, check here https://forum.flutterwave.com/t/international-payment/182 Kindly contact support as suggested.

**Comment by Vorteri** [comment]
OK. Thank you!
